# Generated by Django 3.1.7 on 2021-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20210610_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.CharField(default="dsada", max_length=100),
            preserve_default=False,
        ),
    ]
