# Generated by Django 3.1.7 on 2021-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(default="https://www.google.com/"),
        ),
    ]
